ERROR - 2023-07-03 00:06:51 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\demensia\system\Database\MySQLi\Connection.php:170
Stack trace:
#0 C:\xampp\htdocs\demensia\system\Database\MySQLi\Connection.php(170): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'demensia', 3306, '', 0)
#1 C:\xampp\htdocs\demensia\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\demensia\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\demensia\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\demensia\app\Models\M_Auth.php(19): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\demensia\app\Controllers\Auth.php(94): App\Models\M_Auth->login('ayuagstna@gmail...', 'Sukses1')
#6 C:\xampp\htdocs\demensia\system\CodeIgniter.php(927): App\Controllers\Auth->cek_login()
#7 C:\xampp\htdocs\demensia\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#8 C:\xampp\htdocs\demensia\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\demensia\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\demensia\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\demensia\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\demensia\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\demensia\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\demensia\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\demensia\app\Models\M_Auth.php(19): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\demensia\app\Controllers\Auth.php(94): App\Models\M_Auth->login('ayuagstna@gmail...', 'Sukses1')
#5 C:\xampp\htdocs\demensia\system\CodeIgniter.php(927): App\Controllers\Auth->cek_login()
#6 C:\xampp\htdocs\demensia\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#7 C:\xampp\htdocs\demensia\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\demensia\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\demensia\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-07-03 00:06:51 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `pengguna`
WHERE `email` = :email:
AND `password` = :password:', [...], false)
 3 APPPATH\Models\M_Auth.php(19): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Auth.php(94): App\Models\M_Auth->login('ayuagstna@gmail.com', 'Sukses1')
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Auth->cek_login()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
